---
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app: {{ template "dockerlogindaemonset.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "dockerlogindaemonset.fullname" . }}
data:
  pat: {{ .Values.docker.secret.token | b64enc | quote }}
